### ISSUE TITLE
Place object not working properly

### ISSUE THREAD

**Issue by samaleksandrov** [tue-robotics/nl_robot_console#4]
In the natural language console, when assigned command:
amigo place object (Coke, ice tea) on dinner_table/cabinet,  the robot first lowers it's torso and then tries to place the object on the table, but it's already bellow the level of the table/cabinet.

**Comment by LoyVanBeek** [comment]
Does it successfully place the item?

**Comment by samaleksandrov** [comment]
Nope, it tries to put it below the surface of the cabinet or the table (so I pressed the emergency stop).

**Comment by MatthijsBurgh** [comment]
I think this is fixed, right?

**Comment by LoyVanBeek** [comment]
Apparently not yet. Will look into this tomorrow
