### ISSUE TITLE
ice tea (without "_") not working

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/nl_robot_console#5]
I think spaces are not allowed. This mean that the object_recognition should also only produce labels without spaces.
@Rayman can you check this in the object recognition and change if needed.

**Comment by LoyVanBeek** [comment]
Indeed, object names/labels cannot have spaces because that would make it 2 tokens (ice, tea) instead of one (ice_tea). 

We could also introduce some mapping of machine-readable label (ice_tea) to human-readable label ("ice tea")

**Comment by reinzor** [comment]
This is a problem of this console, the image recognition modules just return a string, spaces should be substituted her if desired.

**Comment by LoyVanBeek** [comment]
Exactly, I only want to adapt the component that cannot handle this, instead of the other way around. 

The substitution should be easy, but it must also be transformed back to having spaces before using it in an object description. I'll take a look tonight maybe

**Comment by reinzor** [comment]
Great!

-Rein

**Comment by LoyVanBeek** [comment]
This is still to be fixed AFAIK, haven't get to it on Friday
